import type { ChatMessage } from './types'

export const ACTIVE_RUN_STATUSES = new Set(['starting', 'running', 'active'])

export const MOCK_DONE_CHAT: ChatMessage[] = [
  {
    id: 'd1',
    role: 'agent',
    body: 'Set up Biome with strict ruleset and wired the script in `package.json`.',
    at: 'Apr 03 · 11:14',
  },
  {
    id: 'd2',
    role: 'user',
    body: 'Looks good. Run a final type check.',
    at: 'Apr 03 · 11:18',
  },
  {
    id: 'd3',
    role: 'agent',
    body: 'tsc clean. All checks passing. Marking complete.',
    at: 'Apr 03 · 11:19',
  },
]

export const WORKING_VERBS = [
  'Accomplishing',
  'Actioning',
  'Actualizing',
  'Baking',
  'Brainstorming',
  'Brewing',
  'Calculating',
  'Cerebrating',
  'Channelling',
  'Churning',
  'Clauding',
  'Coalescing',
  'Cogitating',
  'Computing',
  'Concocting',
  'Conjuring',
  'Considering',
  'Constructing',
  'Contemplating',
  'Cooking',
  'Crafting',
  'Creating',
  'Crunching',
  'Deciphering',
  'Deliberating',
  'Determining',
  'Digesting',
  'Divining',
  'Doing',
  'Effecting',
  'Envisioning',
  'Excavating',
  'Exploring',
  'Finagling',
  'Finessing',
  'Forging',
  'Forming',
  'Frobnicating',
  'Galumphing',
  'Generating',
  'Germinating',
  'Grokking',
  'Hacking',
  'Hatching',
  'Herding',
  'Honking',
  'Hustling',
  'Ideating',
  'Imagining',
  'Incubating',
  'Inferring',
  'Investigating',
  'Manifesting',
  'Marinating',
  'Meandering',
  'Moseying',
  'Mulling',
  'Musing',
  'Noodling',
  'Orchestrating',
  'Percolating',
  'Philosophizing',
  'Plotting',
  'Pondering',
  'Processing',
  'Puttering',
  'Puzzling',
  'Reasoning',
  'Reticulating',
  'Riffing',
  'Ruminating',
  'Scheming',
  'Schlepping',
  'Shimmying',
  'Shucking',
  'Simmering',
  'Smooshing',
  'Spinning',
  'Stewing',
  'Summoning',
  'Synthesizing',
  'Thinking',
  'Tinkering',
  'Transmuting',
  'Unfurling',
  'Unravelling',
  'Untangling',
  'Vibing',
  'Wibbling',
  'Wizarding',
  'Working',
  'Wrangling',
]
